version: "3.8"

services:
  app:
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev"]
    depends_on:
      - stripe

  stripe:
    image: stripe/stripe-cli
    container_name: stripe-cli
    environment:
      - STRIPE_API_KEY=${STRIPE_PRIVATE_KEY}
    command: listen --forward-to http://app:3000/webhook
    volumes:
      - ./.stripe:/root/.config/stripe
