version: "3.8"

services:
  app:
    ports:
      - "3000:3000"
    command: ["node", "dist/server.js"]
# run production build
# docker compose -f docker-compose.yml -f docker-compose.prod.yml up --build
