version: "3.8"

services:
  app:
    build: .
    image: grandbuy-api:latest
    container_name: grandbuy-api-container
    ports:
      - "3000:3000"
    env_file:
      - ./config.env
    volumes:
      - .:/app
      - /app/node_modules
      - ./public:/app/public
    command: ["node", "dist/server.js"]
